export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST'
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE'

export const ADD_TODOS_REQUEST = 'ADD_TODOS_REQUEST'
export const ADD_TODOS_SUCCESS = 'ADD_TODOS_SUCCESS'
export const ADD_TODOS_FAILURE = 'ADD_TODOS_FAILURE'

export const EDIT_TODOS_REQUEST = 'EDIT_TODOS_REQUEST'
export const EDIT_TODOS_SUCCESS = 'EDIT_TODOS_SUCCESS'
export const EDIT_TODOS_FAILURE = 'EDIT_TODOS_FAILURE'

export const DELETE_TODOS_REQUEST = 'DELETE_TODOS_REQUEST'
export const DELETE_TODOS_SUCCESS = 'DELETE_TODOS_SUCCESS'
export const DELETE_TODOS_FAILURE = 'DELETE_TODOS_FAILURE'

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const TOGGLE_SORT = 'TOGGLE_SORT'
export const RESET_TODOS = 'RESET_TODOS'





